###
# Clones or pulls the repo from a public or private Git repository
##
- name: ensure Git is installed via the system package
  apt: 
    name: git-core
    state: present
    update_cache: yes
  become: yes

- name: create git key directory if it does not exist
  file: 
    path: "{{ ansible_env.HOME }}/.ssh/git_key" 
    state: directory

- name: ensure deploy key is on remote server
  copy: 
    src: "{{ github_ssh }}"
    dest: "{{ ansible_env.HOME }}/.ssh/git_key"
    mode: 0600 
    owner: "{{ ansible_user }}"

- name: Install each app
  include_tasks: "install_app.yml app={{ item }}"
  with_items: 
    - "{{ applications }}"