###
# configures the server and installs necessary applications
##
- include: ubuntu.yml
- include: zsh.yml
- include: vim.yml
- include: git.yml
- include: pip.yml

# App specific applications
- include: rf_devices.yml
# - include: playstation_eye.yml

- name: "Reboot"
  command: sleep 1 && reboot
  async: 1
  poll: 0
  ignore_errors: true

- name: "Wait for reboot"
  local_action: wait_for host={{ inventory_hostname }} port=22 state=started delay=10
  become: false

