##
# updates the APT package cache and install packages
##
- apt: update_cache=yes
  become: yes

- name: ensure all standard packages are installed
  apt: name={{item}}
  become: yes
  with_items:
    - python-virtualenv
    - python-dev
    - python-pip
    - xclip

- name: upgrade distro
  apt: upgrade=dist
  become: yes
